/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgregarRouteImport } from './routes/agregar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PracticaRouteImport } from './routes/practica'
import { Route as TarjetasRouteImport } from './routes/tarjetas'
import { Route as CancionSongIdRouteImport } from './routes/cancion.$songId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgregarRoute = AgregarRouteImport.update({
  id: '/agregar',
  path: '/agregar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaRoute = PracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)
const CancionSongIdRoute = CancionSongIdRouteImport.update({
  id: '/cancion/$songId',
  path: '/cancion/$songId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/perfil': typeof PerfilRoute
  '/practica': typeof PracticaRoute
  '/tarjetas': typeof TarjetasRoute
  '/cancion/$songId': typeof CancionSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/perfil': typeof PerfilRoute
  '/practica': typeof PracticaRoute
  '/tarjetas': typeof TarjetasRoute
  '/cancion/$songId': typeof CancionSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/perfil': typeof PerfilRoute
  '/practica': typeof PracticaRoute
  '/tarjetas': typeof TarjetasRoute
  '/cancion/$songId': typeof CancionSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agregar'
    | '/perfil'
    | '/practica'
    | '/tarjetas'
    | '/cancion/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregar'
    | '/perfil'
    | '/practica'
    | '/tarjetas'
    | '/cancion/$songId'
  id:
    | '__root__'
    | '/'
    | '/agregar'
    | '/perfil'
    | '/practica'
    | '/tarjetas'
    | '/cancion/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgregarRoute: typeof AgregarRoute
  PerfilRoute: typeof PerfilRoute
  PracticaRoute: typeof PracticaRoute
  TarjetasRoute: typeof TarjetasRoute
  CancionSongIdRoute: typeof CancionSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agregar': {
      id: '/agregar'
      path: '/agregar'
      fullPath: '/agregar'
      preLoaderRoute: typeof AgregarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica': {
      id: '/practica'
      path: '/practica'
      fullPath: '/practica'
      preLoaderRoute: typeof PracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancion/$songId': {
      id: '/cancion/$songId'
      path: '/cancion/$songId'
      fullPath: '/cancion/$songId'
      preLoaderRoute: typeof CancionSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgregarRoute: AgregarRoute,
  PerfilRoute: PerfilRoute,
  PracticaRoute: PracticaRoute,
  TarjetasRoute: TarjetasRoute,
  CancionSongIdRoute: CancionSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
